/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include <stdbool.h>



#define BLUE_LED_PORT GPIOD
#define BLUE_LED_PIN 15

static void SetSystemClockTo16Mhz(void);
static void ConfigureTim3(void);
static void ConfigureTim4(void);
static void delay( uint32_t ms);

static volatile bool led_on = 0;


int main(void)
{
	SetSystemClockTo16Mhz();
	ConfigureTim3();
	ConfigureTim4();


	//Turn on Blue LED with pure CMSIS
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	GPIOD->MODER |= GPIO_MODER_MODER15_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER15_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_15;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR15_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_1;

	//Configure Orange LED
	GPIOD->MODER |= GPIO_MODER_MODER13_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER13_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_13;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR13_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR13_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR13_1;





    /* Loop forever*/
	while(1)
	{
		GPIOD->BSRR |= GPIO_BSRR_BS_15;
		delay(1000);
		GPIOD->BSRR |= GPIO_BSRR_BR_15;
		delay(4000);

	}
}

static void delay( uint32_t ms ){
	//iterator
	uint32_t i;

	for(i = 0; i <= ms; i++) {
		//Clear the count on the timer
		TIM3->CNT = 0;

		//wait for UIF
		while ((TIM3->SR & TIM_SR_UIF) == 0)
			;

		/* Reset UIF */
		TIM3->SR &= ~TIM_SR_UIF;
	}
}


/*
 * Configure timer 3 so that we can use it for some delays
 */
static void ConfigureTim3(void){
	//enable clock for timer 3
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

	// set a prescaler so we get 1MHz
	//Required freq = CLK / (PSC + 1)
	TIM3->PSC = 15;

	/* (1 MHz / 1000) = 1KHz = 1ms */
	/* So, this will generate the 1ms delay */
	TIM3->ARR = 999;

	/* Finally enable TIM3 module */
	TIM3->CR1 = (1 << 0);
}


/*
 * Configure Timer 4 so we can use it for interrupts
 */
static void ConfigureTim4(void){
	//enable clock for timer 4
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;

	// set a prescaler so we get 1KHz
	//Required freq = CLK / (PSC + 1)
	TIM4->PSC = 15999;

	/* (1 KHz / 1000) = 1Hz = 1s */
	/* So, this will generate the 1s delay */
	TIM4->ARR = 999;

	//Enable timer to generate update events
	TIM4->EGR |= TIM_EGR_UG;

	/* Enable the Interrupt */
	TIM4->DIER |= TIM_DIER_UIE;

	/* Clear the Interrupt Status */
	TIM4->SR &= ~TIM_SR_UIF;

	/* Enable NVIC Interrupt for Timer 4 */
	NVIC_EnableIRQ(TIM4_IRQn);

	/* Finally enable TIM4 module */
	TIM4->CR1 |= TIM_CR1_CEN;
}

void TIM4_IRQHandler(void){
	//check if UIF flag is set
	if(TIM4->SR & TIM_SR_UIF)
	{
		//flip our LED
		led_on = !led_on;

		if(led_on) {
			GPIOD->BSRR |= GPIO_BSRR_BS_13;
		} else {
			GPIOD->BSRR |= GPIO_BSRR_BR_13;
		}
		// Clear Interrupt Flag
		TIM4->SR &= ~(TIM_SR_UIF);
	}

}



/*
 * Function to set system clock to 16MHz
 */
static void SetSystemClockTo16Mhz(void) {

	// check if HSI is ready
	if((RCC->CR & RCC_CR_HSIRDY) == 0){
		//set HSI as clock
		RCC->CR |= RCC_CR_HSION;

		//wait until system clock swaps
		while((RCC->CR & RCC_CR_HSIRDY) == 0);

	}

	//set AHB prescaler to 1
	RCC->CFGR  |= RCC_CFGR_HPRE_DIV1;

	//APB1 prescaler
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV1;

	//APB2 Prescaler
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

	//select HSI as system clock
	RCC->CFGR &= (uint32_t)(uint32_t)~(RCC_CFGR_SW);
	RCC->CFGR |= RCC_CFGR_SW_HSI;

	/* Configure Flash prefetch, Instruction cache, Data cache and wait state */
	FLASH->ACR = FLASH_ACR_ICEN |FLASH_ACR_DCEN |FLASH_ACR_LATENCY_3WS;


	/* Disabling HSE Clock*/
	RCC->CR &= ~RCC_CR_HSEON;



}






